name: rutsnrides_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5
  dio: ^5.9.0
  gsheets: ^0.5.0
  table_calendar: ^3.0.9
  flutter_form_builder: any
  intl: ^0.18.1
  pdf: ^3.11.0
  printing: ^5.11.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/google_credentials.json
