name: Flutter CI/CD - Firebase Distribution

on:
  push:
    branches:
      - github_cicd   # run when code is pushed to github_cicd branch
  pull_request:
    branches:
      - github_cicd   # run when a PR is opened against github_cicd branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 

      - name: Install dependencies
        run: flutter pub get

      # 👇 Decode keystore from GitHub Secret
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      # 👇 Build signed release APK
      - name: Build APK
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
